"""Build fixtures/sample.db from the board's sensor_data.db.

Run on the board (read-only on the source):
    .venv/bin/python tests/make_fixture.py --db sensor_data.db --nodes nodes.json \
        --out /tmp/fixture --days 30
then copy /tmp/fixture/{sample.db,nodes.json,FIXTURE.md} into hub/fixtures/.

What it keeps on purpose: the last N days ending at MAX(ts) (deterministic),
every row including out-of-range sensor values, nodes that stopped reporting,
and receive-time timestamps. Node ids are anonymised (env_01.., vis_01..) but the
env<->vision pairing through the shared label is preserved in nodes.json.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from datetime import UTC, datetime, timedelta
from pathlib import Path

TS_FMT = "%Y-%m-%d %H:%M:%S"


def anonymise(env_nodes: list[str], vis_nodes: list[str]) -> dict[str, str]:
    mapping = {n: f"env_{i:02d}" for i, n in enumerate(sorted(env_nodes), 1)}
    mapping.update({n: f"vis_{i:02d}" for i, n in enumerate(sorted(vis_nodes), 1)})
    return mapping


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", required=True)
    ap.add_argument("--nodes", required=True, help="nodes.json with real ids -> labels")
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("--days", type=int, default=30)
    a = ap.parse_args()

    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    dst_path = out / "sample.db"
    if dst_path.exists():
        dst_path.unlink()

    src = sqlite3.connect(f"file:{Path(a.db).resolve().as_posix()}?mode=ro", uri=True)
    end = src.execute("SELECT MAX(ts) FROM readings").fetchone()[0]
    start = (datetime.strptime(end, TS_FMT) - timedelta(days=a.days)).strftime(TS_FMT)

    env_nodes = [r[0] for r in src.execute("SELECT DISTINCT node FROM readings")]
    vis_nodes = [r[0] for r in src.execute("SELECT DISTINCT node FROM occupancy")]
    mapping = anonymise(env_nodes, vis_nodes)
    labels = json.loads(Path(a.nodes).read_text())
    anon_labels = {mapping[k]: v for k, v in labels.items() if k in mapping}

    dst = sqlite3.connect(dst_path)
    for table in ("readings", "occupancy"):
        ddl = src.execute("SELECT sql FROM sqlite_master WHERE name=?", (table,)).fetchone()[0]
        dst.execute(ddl)
    dst.commit()

    stats: dict[str, dict] = {}
    for table in ("readings", "occupancy"):
        cols = [c[1] for c in src.execute(f"PRAGMA table_info({table})")]
        node_i = cols.index("node")
        rows = src.execute(
            f"SELECT {','.join(cols)} FROM {table} WHERE ts >= ? AND ts <= ? ORDER BY id",
            (start, end),
        )
        ph = ",".join("?" * len(cols))
        n = 0
        for r in rows:
            r = list(r)
            r[node_i] = mapping[r[node_i]]
            dst.execute(f"INSERT INTO {table}({','.join(cols)}) VALUES({ph})", r)
            n += 1
        dst.commit()
        per_node = dst.execute(
            f"SELECT node, COUNT(*), MIN(ts), MAX(ts) FROM {table} GROUP BY node"
        ).fetchall()
        stats[table] = {"rows": n, "per_node": per_node}

    bad = dst.execute("SELECT COUNT(*) FROM readings WHERE co2 <= 0 OR sen_temp < -50").fetchone()[
        0
    ]
    dst.execute("VACUUM")
    dst.close()

    (out / "nodes.json").write_text(json.dumps(anon_labels, indent=2) + "\n")
    lines = [
        "# fixtures/sample.db",
        "",
        f"Generated by tests/make_fixture.py on {datetime.now(UTC).strftime(TS_FMT)} UTC "
        f"from the board DB. Window: {start} .. {end} ({a.days} days, ending at MAX(ts)).",
        f"Size: {dst_path.stat().st_size / 1e6:.1f} MB. Out-of-range rows kept: {bad}.",
        "Node ids anonymised; env<->vision pairing preserved via nodes.json labels.",
        "",
    ]
    for table, s in stats.items():
        lines.append(f"## {table} ({s['rows']} rows)")
        lines.append("| node | rows | min ts | max ts |")
        lines.append("|---|---|---|---|")
        for node, cnt, lo, hi in s["per_node"]:
            lines.append(f"| {node} | {cnt} | {lo} | {hi} |")
        lines.append("")
    (out / "FIXTURE.md").write_text("\n".join(lines))
    print(
        json.dumps(
            {
                "window": [start, end],
                "bad_rows": bad,
                "rows": {t: s["rows"] for t, s in stats.items()},
                "size_mb": round(dst_path.stat().st_size / 1e6, 2),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
